### ISSUE TITLE
logstage 0.8.7 does not support java 8

### ISSUE THREAD

**Issue by sim732** [7mind/izumi#595] opened 2019-07-26 12:44 UTC
Hi,

while testing i got the following error: 
[info] Running net.uptel.sim.TestLogStage 
[error] (run-main-0) java.lang.NoSuchMethodError: java.util.concurrent.atomic.AtomicInteger.weakCompareAndSetVolatile(II)Z
[error] java.lang.NoSuchMethodError: java.util.concurrent.atomic.AtomicInteger.weakCompareAndSetVolatile(II)Z
[error] 	at com.github.pshirshov.izumi.logstage.api.rendering.logunits.Styler$AdaptivePad.transform(Styler.scala:64)

**Comment by pshirshov** [comment] 2019-07-26 13:28
Hi, 

this should be fixed once we merge the p/r with scalajs support

**Comment by neko-kai** [comment] 2019-07-26 18:57
Actually this is caused by overly aggressive inliner settings in release, Scala inliner ended-up inlining the implementation of standard library Java method `.updateAndGet` (that IS available in Java 8) –
<img width="1050" alt="Screenshot 2019-07-26 at 19 48 21" src="https://user-images.githubusercontent.com/450507/61974657-fb95a680-afde-11e9-8820-3db8823edacd.png">

**Closed as completed** 2019-07-26 18:58 UTC
