### ISSUE TITLE
Distage fails when it encounters some annotated classes

### ISSUE THREAD

**Issue by redvasily** [7mind/izumi#739] opened 2019-11-20 17:28 UTC
It seems that certain annotations can pose difficulties for distage.

The exception that I get is just this:

`scala.reflect.internal.Symbols$CyclicReference: illegal cyclic reference involving class InterfaceStability`

And somehow that's a full stacktrace.

I get this when I try to `make` some Kafka classes. In this particular case, the code is basically just this:
```
object StreamsResetterModule extends ModuleDef {
  make[kafka.tools.StreamsResetter]
}
```

But this happens with many other classes from Kafka packages as well. 

It seems that there's something wrong with scala reflection and InterfaceStability annotations. (org.apache.kafka.common.annotation.InterfaceStability)

Here are those classes: 
https://github.com/apache/kafka/blob/c87fe9402cbebc460b42cd3dd7c268e5e6e659d9/core/src/main/scala/kafka/tools/StreamsResetter.java
https://github.com/apache/kafka/blob/f98e176746d663fadedbcd3c18312a7f476a20c8/clients/src/main/java/org/apache/kafka/common/annotation/InterfaceStability.java

I guess it happens because of InterfaceStability annotation on the InterfaceStability annotation itself.

Right now you have to find workarounds for that. I.e. you can't really let distage touch this InterfaceStability in any way: either you have to construct these dependencies "on the spot" or I guess hiding them under AnyRef should also work.

**Comment by neko-kai** [comment] 2019-11-20 18:47
@redvasily 
Is there any way you could make a self-contained reproduction?
For kafka types in question, does it work if you construct them by lambda or no? e.g.

```scala
make[kafka.tools.StreamsResetter].from {
  new kafka.tools.StreamsResetter
}
```

Also, does the following fail with an exception?

```scala
object app1 extends App {
  println(scala.reflect.runtime.universe.typeOf[kafka.tools.StreamsResetter])
}
```

And does the following?

```scala
object app2 extends App {
  println(izumi.fundamentals.reflection.LTT[kafka.tools.StreamsResetter])
}
```

**Comment by redvasily** [comment] 2019-11-21 14:10
Here's a standalone repository that demonstrates the problem: https://github.com/redvasily/distage-interface-stability-test

```scala
object app1 extends App {
  println(scala.reflect.runtime.universe.typeOf[kafka.tools.StreamsResetter])
}
```
Throws the same exception. So it seems to me that it's the source of this problem.

While the following code works just fine (prints the class name)
```scala
object app1 extends App {
  println(izumi.fundamentals.reflection.LTT[kafka.tools.StreamsResetter])
}
```

**Comment by neko-kai** [comment] 2019-11-21 14:27
@redvasily 
> Throws the same exception. So it seems to me that it's the source of this problem.

Oh well, this would need a bug report in Scala repo: https://github.com/scala/bug/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Areflection
However, `scala-reflect` is essentially abandoned and even if the issue is fixed that would take a lot of time until next Scala release. Your best bet currently is to wrap these types in your own types and bind the wrappers –
```scala
import kafka.tools.StreamsResetter

final case class StreamResetterWrapper(value: StreamsResetter) extends AnyVal

make[StreamResetterWrapper].from(StreamResetterWrapper(new StreamsResetter))
```

If you don't want to write down the constructors of these types manually, the following MIGHT also work, but I don't know for sure:

```scala
import scala.reflect.runtime.{universe => ru}
import izumi.distage.constructors.ConcreteConstructor

// prevent scala-reflect from trying to inspect StreamsResetter
implicit val typeTagBad: ru.TypeTag[StreamsResetter] = null

// generate constructor for StreamsResetter
val ctor1: ProviderMagnet[StreamsResetter] = ConcreteConstructor[StreamsResetter].get

// wrap result in wrapper to hide the type
val ctor: ProviderMagnet[StreamResetterWrapper] =  ctor1.map(StreamResetterWrapper(_))

// bind
make[StreamResetterWrapper].from(ctor)
```

**Comment by neko-kai** [comment] 2019-11-21 14:28
@redvasily 
As aside, distage 0.10 will not depend on scala-reflect, since we're moving to [our own reflection infrastructure](https://blog.7mind.io/lightweight-reflection.html), so won't have this issue. WIP currently https://github.com/7mind/izumi/issues/594

**Comment by neko-kai** [comment] 2019-12-04 21:28
@redvasily Could you check if `0.10.0-M1` has fixed this issue? It should also fix the slow test startups we discussed on Gitter.

**Comment by redvasily** [comment] 2019-12-05 13:33
@neko-kai 
It seems that this problem is gone in `0.10.0-M1` and `0.10.0-M2`.

On the other hand I don't see much performance improvements. Still takes about 2 seconds on my machine to construct an Injector instance.

And more importantly in my "big app", I see lots of error messages with 0.10. Mostly related to akka actors.

Errors like this (from akka untyped actors)
```
ActorRegistryModule.scala:8: illegal inheritance;
[error]  self-type akka.actor.ActorRef does not conform to akka.actor.ActorRef's selftype akka.actor.InternalActorRef
[error]   make[ActorRef].named("registry").from((actorSystem: ActorSystem) => {
```

And like this (from akka typed actors):
```
KeeperModule.scala:12: not enough arguments for constructor Behavior: (_tag: Int)akka.actor.typed.Behavior[fr.cfm.risk.metricengine.actors.Keeper.Message].
[error] Unspecified value parameter _tag.
[error]   make[Behavior[Keeper.Message]].from({ consumerFactory: KeeperConsumer.Factory => Keeper(consumerFactory)
```

**Comment by redvasily** [comment] 2019-12-05 13:33
This bug seems to have been fixed.

**Closed as completed** 2019-12-05 13:33 UTC
Labels: bug, distage (di), scala-reflect

**Comment by neko-kai** [comment] 2019-12-08 00:40
@redvasily 
> On the other hand I don't see much performance improvements. Still takes about 2 seconds on my machine to construct an Injector instance.
> And more importantly in my "big app", I see lots of error messages with 0.10. Mostly related to akka actors.

Could you please check `0.10.0-M3` ? Should fix both of these issues (hopefully)

**Comment by redvasily** [comment] 2019-12-09 12:08
@neko-kai 
`0.10.0-M3` works fine for me. The above mentioned errors are gone. My "big app" works fine. Even `.unresovledImports` works just fine. 

The performance has improved. `Injector()` construction is about twice faster than 0.9. It takes now about a second on my machine, and the improvement is quite noticeable.

**Comment by neko-kai** [comment] 2019-12-09 19:11
@redvasily 
> Even .unresovledImports works just fine.

There's a short-hand `.assertImportsResolvedOrThrow` now!  https://izumi.7mind.io/latest/release/doc/distage/debugging.html#testing-plans

> It takes now about a second on my machine, and the improvement is quite noticeable.

Hmm, if you could profile it, that'd be great. I tried to and shaved off 100ms on my machine (from 400ms to 300ms for first `Injector()` call) – please check `0.10.0-M5`, but it seems like the rest is either just classloading or it doesn't show up in the profile otherwise...

You could also try using [Class Data Sharing](https://openjdk.java.net/jeps/310) `-Xshare:dump` / `-XX:+UseAppCDS` with subsequent `-Xshare:on` and check if that impacts start-up times for you, ostensibly these options are there for caching classloading & warmup time.

**Comment by pshirshov** [comment] 2019-12-09 21:36
So, apart of making some more or less obvious optimizaitons (you should expect ~15% improvement in `0.10.0-M6`), I've made a simple benchmark:

```
object InjectorPerf {
  def main(args: Array[String]): Unit = {
    println("[IPT] About to start...")
    for (x <- 0 to 500){
      val t1 = System.nanoTime()
      Injector()
      val t2 = System.nanoTime()
      if (x % 100 == 0) {
        println(s"[IPT]  ${(t2 - t1) / 1000.0 / 1000.0}")
      }
    }
    println("[IPT] finished!")

  }
}
```

The output on my machine is 

```
[IPT] About to start...
[IPT]  581.041096
[IPT]  3.551864
[IPT]  2.685096
[IPT]  2.012205
[IPT]  1.86207
[IPT]  1.4845329999999999
[IPT] finished!
```

And I think that these numbers are pretty good.

In case I run it with `-Xlog:class+load=info` there are A LOT of classes loaded in between of first two messages (see the attachment)

[injector-bootstrap-perf.txt](https://github.com/7mind/izumi/files/3941811/injector-bootstrap-perf.txt)

So, I'm inclined to think that it's all about classloading so there isn't much we can do. We may try to reduce amount of classes in distage itself, but it's pricy job - we would have to delambdify all the code... All for a hundred of milliseconds.

Classpath caching should help though it's bit untrivial to use, so I will test it and share my results bit later.

**Comment by pshirshov** [comment] 2019-12-09 21:41
Also I got ~20% improvement running my test with `-noverify` option. Try it!

(by the way, these percentages are based on several runs, so you shouldn't worry about accidental fluctuations)

So, typical output with `-noverify` is:

```
[IPT] About to start...
[IPT]  428.992932
[IPT]  2.7342910000000002
[IPT]  2.347353
[IPT]  2.270945
[IPT]  2.377714
[IPT]  1.611537
[IPT] finished!
```

And it kinda confirms that it's all about classloading.

**Comment by pshirshov** [comment] 2019-12-09 22:06
So, I got 30-50% improvement (yup, halved the time) by using class cache.

Here is my test script: [perf.txt](https://github.com/7mind/izumi/files/3941925/perf.txt)

Without cache:
```
[IPT] About to start...
[IPT]  305.712338
[IPT]  1.461822
[IPT]  1.256772
[IPT]  1.26
[IPT]  0.88847
[IPT]  0.758231
[IPT] finished!
```

With cache:
```
[IPT] About to start...
[IPT]  206.461817
[IPT]  1.537837
[IPT]  1.348112
[IPT]  1.180705
[IPT]  0.9787899999999999
[IPT]  0.948579
[IPT] finished!
```

Unfortunately such a solution wouldn't work well for your development process but may be useful for production in case startup time is critical for you.

**Comment by pshirshov** [comment] 2019-12-09 22:14
Also, in case you use JDK 12+ you may try to use AOT: https://www.baeldung.com/ahead-of-time-compilation

**Comment by pshirshov** [comment] 2019-12-09 23:56
Just in case, the results above are for `0.10.0-M5`

`0.10.0-M6` shows better numbers:

Without cache:
```
[IPT] About to start...
[IPT]  286.428532
[IPT]  2.515085
[IPT]  2.25436
[IPT]  1.728001
[IPT]  2.314618
[IPT]  1.124771
[IPT] finished!
```

with cache:

```
[IPT] About to start...
[IPT]  185.251039
[IPT]  2.484107
[IPT]  1.962484
[IPT]  1.582826
[IPT]  1.7354349999999998
[IPT]  1.594278
[IPT] finished!
```

**Comment by redvasily** [comment] 2019-12-10 08:43
Thanks for looking into this. I get 0.8 seconds now with `0.10.0-M6`. Which is pretty good for me.

**Comment by pshirshov** [comment] 2019-12-10 11:24
Just out of curiosity, have you tried `-noverify`?

Also, I would like to look at your numbers with -Xshare:on

**Comment by redvasily** [comment] 2019-12-10 15:26
I've tried `-noverify` and it does help to the tune of (10-15)%. Couldn't get AppCDS to work on my Oracle JDK8, but I got it working on Java 13 (java.net from sdkman). Just switching to JDK13 improves startup performance to 600ms (which is faster than JDK8 with `-noverify`), JDK13 + AppCDS is roughly 350ms for me. All and all pretty good.
