### ISSUE TITLE
Maybe preserve doc comments in target languages?

### ISSUE THREAD

**Issue by neko-kai** [7mind/izumi#206] opened 2018-06-03 07:26 UTC
That is, given input

```izumi
data Pet {
  /** Name of the pet **/
  name: str
  /** Species of the pet, can be one of `Python`, `Doge`, `Gopher`, `Crustacean`, `Neko`, `Pony` **/
  _: PetType
}
```

generate output:

```scala
final case class Pet(
  /** Name of the pet **/
  name: String,
  /** Species of the pet, can be one of `Python`, `Doge`, `Gopher`, `Crustacean`, `Neko`, `Pony` **/
  petType: PetType
)
```

This would allow us to generate documentation for clients directly using the target language's doc tool. This might or might not be preferable to creating our own doctool.

We could also allow out of line doc comments - that is, allowing doc comments to be placed not directly on the definition, to remove line noise:

```izumi
data Pet {
  name: str
  _: PetType
}

/** @Pet.name 
  Name of the pet **/
/** @Pet.petType
  Species of the pet, can be one of `Python`, `Doge`, `Gopher`, `Crustacean`, `Neko`, `Pony` **/
```

**Comment by pshirshov** [comment] 2018-07-04 15:42
Duplicate of #113

**Closed as completed** 2020-01-14 23:34 UTC
Labels: enhancement, idl, high-prio
