### ISSUE TITLE
distage named instances handling regression after 0.9.12 (0.9.16 for sure)

### ISSUE THREAD

**Issue by redvasily** [7mind/izumi#762] opened 2019-12-02 17:58 UTC
Hello,

I have a class roughly like this:

```scala
class MyClass(a: String @Id("a"), b: String @Id("b")) { ... }
```
which is wired like this:

```scala
object MyClassModule extends ModuleDef {
  make[MyClass]
}

object ConfigModule extends ModuleDef {
  make[String].named("a").from(whatever())
  make[String].named("b").from { a: String @Id("a") => f(a) }
}
```

And it works just fine with distage 0.9.12

However with distage 0.9.16, it doesn't work I get an error message like this:
```
Provisioner stopped after 1 instances, 2/23 operations failed: 
 - {type.scala.Predef::java.lang.String@a} (MyClassModule.scala:20), MissingInstanceException: Instance is not available in the object graph: {type.scala.Predef::java.lang.String@applicationId}. required by refs: Set({type.MyClass})
 - {type.scala.Predef::java.lang.String@b} (MyClassModule.scala:20), MissingInstanceException: Instance is not available in the object graph: {type.scala.Predef::java.lang.String@b}. required by refs: Set({type.MyClass})
```

However I can get it to work using distage 0.9.16 if I change how MyClass is wired:

```scala
object MyClassModule extends ModuleDef {
  make[MyClass].from { (a: String @Id("a"), b: String @Id("b")) => new MyClass(a, b) }
}
```

Here are some fragments of distage's plan on 0.9.16 (when distage is not able to wire all of the instances normally):

```
{type.scala.Predef::java.lang.String@a} (MyClassModule.scala:20) := import {type.scala.Predef::java.lang.String@b} // required for {type.MyClass}
{type.scala.Predef::java.lang.String@b} (MyClassModule.scala:20) := import {type.scala.Predef::java.lang.String@b} // required for {type.MyClass}

{type.java.lang.String@a} (ConfigModule.scala:29) := call(izumi.distage.model.definition.dsl.ModuleDefDSL$BindDSLBase$$Lambda$632/740480756@2975d1d1(): java.lang.String) {}

{type.java.lang.String@b} (ConfigModule.scala:31) := call(ConfigModule$$$Lambda$650/1431885203@61e386cf(java.lang.String): java.lang.String) {
  arg a: java.lang.String = lookup({type.java.lang.String@a})
}

{type.MyClass} (MyClassModule.scala:20) := make[MyClass] (
  arg a: scala.Predef::java.lang.String = lookup({type.scala.Predef::java.lang.String@a})
  arg b: scala.Predef::java.lang.String = lookup({type.scala.Predef::java.lang.String@b})
)

```

Seemingly I have supplied all necessary instances/rules/etc, which is further confirmed by the fact that it works without any modifications with 0.9.12. Also it's possible to get this code to work with 0.9.16 by doing some modifications that shouldn't affect anything.

**Comment by neko-kai** [comment] 2019-12-02 18:34
@redvasily 
Looking at the plan I can see that the references to `String` have different types, MyClass reports `Predef::String`, while the parameters are assigned to `java.lang.String`. This is probably the root cause. However, the only way I could make `Predef.String` appear is by writing `String` with an additional empty refinement like `(String {}) @Id`: 

```scala
    class MyClass(val a: (scala.Predef.String {}) @Id("a"), val b: String @Id("b"))

    object MyClassModule extends ModuleDef {
      make[MyClass]
    }

    object ConfigModule extends ModuleDef {
      make[scala.Predef.String].named("a").from("applicationId")
      make[Predef.String].named("b").from { a: String @Id("a") => a }
    }
```
```
{type.scala.Predef::java.lang.String@a} (BasicCases.scala:109) := import {type.scala.Predef::java.lang.String@a} // required for {type.izumi.distage.fixtures.BasicCases::izumi.distage.fixtures.BasicCases.BasicCaseIssue762::izumi.distage.fixtures.BasicCases.BasicCaseIssue762.MyClass}
{type.java.lang.String@a} (BasicCases.scala:113) := call(izumi.distage.model.providers.ProviderMagnet$$$Lambda$421/0x00000008014f2040@6622a690(): java.lang.String) {}
{type.java.lang.String@b} (BasicCases.scala:114) := call(izumi.distage.fixtures.BasicCases$BasicCaseIssue762$ConfigModule$$$Lambda$426/0x0000000801517040@497570fb(java.lang.String): java.lang.String) {
  arg a: java.lang.String = lookup({type.java.lang.String@a})
}
{type.izumi.distage.fixtures.BasicCases::izumi.distage.fixtures.BasicCases.BasicCaseIssue762::izumi.distage.fixtures.BasicCases.BasicCaseIssue762.MyClass} (BasicCases.scala:109) := make[izumi.distage.fixtures.BasicCases::izumi.distage.fixtures.BasicCases.BasicCaseIssue762::izumi.distage.fixtures.BasicCases.BasicCaseIssue762.MyClass] (
  arg a: scala.Predef::java.lang.String = lookup({type.scala.Predef::java.lang.String@a})
  arg b: java.lang.String = lookup({type.java.lang.String@b})
)
```

Only the weirldly written `a` parameter got `Predef.String`, it doesn't seem to happen to any other Strings...

Anyway, I think it's possible to rule out this situation...

**Comment by redvasily** [comment] 2019-12-03 09:40
This problems seems to have been fixed in 0.9.17

**Comment by neko-kai** [comment] 2019-12-03 11:48
@redvasily 
👍 
Could you close the issue when you confirm it's working?

**Comment by redvasily** [comment] 2019-12-03 14:48
Works fine for me with distage 0.9.17

**Closed as completed** 2019-12-03 14:48 UTC
Labels: bug, distage (di), high-prio
